name: 'Test Coverage at Comment'
description: '-'
author: 'Kuncoro Wicaksono'
inputs:
  pytest-coverage:
    description: 'Where to find the txt output of pytest-coverage'
    required: true
    default: 'output.txt'
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
